name: MSBuild

on: 
  pull_request:
  push:
  release:
    types: published

env:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
       platform: [Win32]
       buildtype: [Debug, Release]
    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1  
    - uses: actions/checkout@v2
      with:
       submodules: 'true'
    - name: Configure build
      run: |
        ./premake5
    - name: Build
      run: |
        msbuild -m project_files/iv-language-loader.sln /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
   - name: Upload artifact to actions
     uses: actions/upload-artifact@v2
     with:
       name: iv-language-loader_${{matrix.buildtype}}_${{matrix.platform}}
       path: ./output/asi/*
